
(()=>{const $=(s,c=document)=>c.querySelector(s),$$=(s,c=document)=>[...c.querySelectorAll(s)],D=(window.ACJ_DATA||{}).properties||[],C=window.ACJ_CONFIG||{};
const money=n=>new Intl.NumberFormat('pt-BR',{style:'currency',currency:'BRL',maximumFractionDigits:0}).format(n), digits=v=>String(v||'').replace(/\D/g,'');
const header=$('.header');addEventListener('scroll',()=>header?.classList.toggle('scrolled',scrollY>30),{passive:true});$('.menu')?.addEventListener('click',()=>document.body.classList.toggle('menu-open'));
const io=new IntersectionObserver(es=>es.forEach(e=>{if(e.isIntersecting){e.target.classList.add('visible');io.unobserve(e.target)}}),{threshold:.12});$$('.reveal').forEach(x=>io.observe(x));
const list=$('#projectList');if(list){list.innerHTML=D.map((p,i)=>`<a class="project" href="empreendimento.html?id=${p.id}"><span class="project-index">0${i+1}</span><h3>${p.title}</h3><span class="project-meta">${p.district} · ${p.area} m² · ${p.beds} dorm.</span><span class="project-status">${p.status} ↗</span></a>`).join('');if(D[0])$('#projectPreview').style.backgroundImage=`url('${D[0].hero}')`;$$('.project').forEach((el,i)=>el.addEventListener('mouseenter',()=>$('#projectPreview').style.backgroundImage=`url('${D[i].hero}')`))}
const cards=$('#cards');function render(){if(!cards)return;let rows=D,st=$('#status')?.value||'',ty=$('#type')?.value||'';rows=rows.filter(p=>(!st||p.status===st)&&(!ty||p.type===ty));cards.innerHTML=rows.map(p=>`<a class="card" href="empreendimento.html?id=${p.id}" style="background-image:url('${p.hero}')"><div class="card-info"><small>${p.status} · ${p.district}</small><h3>${p.title}</h3><div class="card-meta"><span>${p.area} m²</span><span>${p.beds} dorm.</span><span>${money(p.price)}</span></div></div></a>`).join('')}render();['status','type'].forEach(x=>$('#'+x)?.addEventListener('change',render));
const id=new URLSearchParams(location.search).get('id');if(id&&$('#detailTitle')){let p=D.find(x=>x.id===id)||D[0];$('#detail').style.backgroundImage=`url('${p.hero}')`;$('#detailTitle').textContent=p.title;$('#detailLoc').textContent=`${p.district} · ${p.city}`;$('#detailMeta').innerHTML=`<span>${p.area} m²</span><span>${p.beds} dormitórios</span><span>${p.suites} suítes</span><span>${p.parking} vagas</span><span>${money(p.price)}</span>`;$('#detailDesc').textContent=p.description;$('#gallery').innerHTML=p.gallery.map(x=>`<img src="${x}" alt="${p.title}">`).join('')}
$$('form[data-lead-form]').forEach(f=>f.addEventListener('submit',e=>{e.preventDefault();if(!f.reportValidity())return;let fd=new FormData(f),msg=[`Olá, ACJ Prime! Tenho interesse em ${f.dataset.leadForm}.`,...[...fd.entries()].map(([k,v])=>`${k}: ${v}`)].join('\n'),wa=digits(C.whatsapp);if(wa)open(`https://wa.me/${wa}?text=${encodeURIComponent(msg)}`,'_blank');else $('.feedback',f).textContent='Formulário pronto. O WhatsApp será conectado em config.js.'}))
})();
